### ISSUE TITLE
Qnap installation

### ISSUE THREAD

**Issue by aerinspect** [mandarons/icloud-docker#135]
**Use case**
As a qnap user, but a docker newby, I want to install iCloud-drive on my docker installation which is installed on the Qnap.

**Describe the solution you'd like**
An elaborate How-to that I can follow to get this installed.

**Describe alternatives you've considered**

**Additional context**
I do not mind to share all that I have learned for other Qnap users

**Comment by mandarons** [comment]
The README outlines installation instructions using both - docker and docker compose.

What's the error are you seeing?

**Comment by aerinspect** [comment]
Hi,

I try to installed it via docker compose.
- I've created the diretcories on my NAS: /share/homes/****/icloud (config.yaml  data/ are inside that directory)
- I run this via the docker compose example

Error: failed to deploy a stack: time="2023-03-25T18:45:15Z" level=warning msg="The \"PWD\" variable is not set. Defaulting to a blank string." time="2023-03-25T18:45:15Z" level=warning msg="The \"PWD\" variable is not set. Defaulting to a blank string." time="2023-03-25T18:45:15Z" level=warning msg="The \"PWD\" variable is not set. Defaulting to a blank string." time="2023-03-25T18:45:15Z" level=warning msg="The \"user\" variable is not set. Defaulting to a blank string." time="2023-03-25T18:45:15Z" level=warning msg="The \"user\" variable is not set. Defaulting to a blank string." open /data/compose/9/.env.icloud: no such file or directory

**Comment by mandarons** [comment]
1. Run `id` command and note down `uid` as `PUID` and `gid` as `GUID`. Use it in environment section of below compose file. 
2. Run `echo "ENV_ICLOUD_PASSWORD=<your iCloud password>" >> .env.icloud`. 
3. Try below `docker-compose.yaml`
```docker
version: "3.4"
services:
  icloud:
    image: mandarons/icloud-drive
    environment:
      - PUID=<insert the output of `id` uid value>
      - GUID=<insert the output of `id` gid value>
    env_file:
      - .env.icloud #should contain ENV_ICLOUD_PASSWORD=<password>
    container_name: icloud
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /share/homes/****/icloud/config.yaml:/app/config.yaml
      - /share/homes/****/icloud/data:/app/icloud
      - /share/homes/****/icloud/session_data:/app/session_data
```
I never used QNAP system. So let's see if this resolves your problem.

**Comment by antoniogiroz** [comment]
I also tried to use this docker in a QNAP, but I got another error. This is my config:

```yml
# docker-compose.yaml
version: "3.4"
services:
  icloud:
    image: mandarons/icloud-drive
    container_name: icloud-drive
    environment:
      - PUID=$PUID
      - GUID=$GUID
      - ENV_ICLOUD_PASSWORD=$ENV_ICLOUD_PASSWORD
      - ENV_CONFIG_FILE_PATH=$ENV_CONFIG_FILE_PATH
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/config.yaml:/app/config.yaml
      - ${PWD}/data:/app/icloud
      - ${PWD}/session_data:/app/session_data
```

```sh
# Environment variables
PUID=1000
GUID =100
ENV_ICLOUD_PASSWORD=<my-apple-password>
ENV_CONFIG_FILE_PATH=/share/containers/icloud-drive/config.yaml
PWD=/share/containers/icloud-drive
```

```yml
# config.yaml. It's in /share/containers/icloud-drive/config.yaml
app:
  logger:
    level: "info"
    filename: "icloud.log"
  credentials:
    username: "<my-apple-email>"
    retry_login_interval: 600
  # Drive destination
  root: "/share/containers/icloud-drive"
  region: global
drive:
  destination: "/share/Backups/iCloud"
  remove_obsolete: false
  sync_interval: 300
photos:
  destination: "/share/Backups/iCloud/photos"
  remove_obsolete: false
  sync_interval: 500
``` 

With this config I got these error messages:

```
Loading config from /app/config.yaml ...
Config file not found at /share/containers/icloud-drive/config.yaml.
2023-12-17 07:43:43,995 :: WARNING :: root :: config_parser.py :: 115 :: Warning: root destination is missing in app > root. Using default root destination: ./icloud
2023-12-17 07:43:43,998 :: ERROR :: root :: config_parser.py :: 42 :: username is missing in app > credentials > username. Please set the username.
Traceback (most recent call last):
  File "/app/./src/main.py", line 7, in <module>
    sync.sync()
  File "/app/src/sync.py", line 120, in sync
    if "drive" not in config and "photos" in config:
TypeError: argument of type 'NoneType' is not iterable
```

<img width="789" alt="image" src="https://github.com/mandarons/icloud-drive-docker/assets/520071/37b7cf97-fce9-4db9-a6e3-f2636bbc1872">
