### ISSUE TITLE
[BUG] login with App-Passwords not working

### ISSUE THREAD

**Issue by knmax** [mandarons/icloud-docker#142]
**Describe the bug**
When starting the container I receive the following error:
2023-08-19 20:55:09,745 :: ERROR :: icloudpy.base :: base.py :: 186 :: Missing apple_id field

**To Reproduce**

Start container with docker compose up

**Expected behavior**
start of the container and run

**Screenshots**
<img width="1157" alt="Bildschirmfoto 2023-08-19 um 22 59 04" src="https://github.com/mandarons/icloud-drive-docker/assets/74471312/b148e7e0-9f04-4ae1-9e4d-d6cb25459e6a">

**Configuration**
If applicable, please share the configuration details

app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "icloud.log"
  credentials:
    # iCloud drive username
    username: "my-apple-id"
    # Retry login interval - default is 10 minutes
    retry_login_interval: 600
  # Drive destination
  root: "icloud"
  smtp:
    ## If you want to receive email notifications about expired/missing 2FA credentials then uncomment
    # email: "user@test.com"
    ## optional, to email address. Default is sender email.
    # to: "receiver@test.com"
    # password:
    # host: "smtp.test.com"
    # port: 587
    # If your email provider doesn't handle TLS
    # no_tls: true
  region: global # For China server users, set this to - china (default: global)
drive:
  destination: "drive"
  remove_obsolete: false
  sync_interval: 300
  #filters: # Optional - use it only if you want to download specific folders.
    # File filters to be included in syncing iCloud drive content
   #folders:
    #  - "folder1"
    #  - "folder2"
    #  - "folder3"
    #file_extensions:
      # File extensions to be included
    #  - "pdf"
    #  - "png"
    #  - "jpg"

**Comment by mandarons** [comment]
Login manually if ENV_ICLOUD_PASSWORD is not specified and/or 2FA is required
```
docker exec -it icloud /bin/sh -c "icloud --username=<icloud-username> --session-directory=/app/session_data"
```

**Comment by knmax** [comment]
I‘m sorry - apparently I forgot to mention, I have already used the ENV_ICLOUD_PASSWORD in my .env.icloud
Do I need to add a seperate ENV value for the appleid itself?

**Comment by mandarons** [comment]
No. You don't need apple ID environment variable. It takes from the config.yaml file. Please still try manually logging in using below command: 
```docker exec -it icloud /bin/sh -c "icloud --username=<icloud-username> --session-directory=/app/session_data"```
If it still doesn't work, please share your docker compose file.

**Comment by knmax** [comment]
Thanks for the feedback.
I managed to put in the command while the container was starting - it seems as it is doing something now - at least when I pull up docker container stats it shows the container being active every few seconds, before it was just stuck at 0.
Is there any way how I can verify if it is working or not?

**Comment by mandarons** [comment]
Please share your docker-compose file. What you're experiencing is highly unusual.

**Comment by knmax** [comment]
I hope this helps to figure out was is going on...
I start the container either by using "docker compose up" directly in the folder or I use "docker container start icloud"
[icloud-drive-docker.zip](https://github.com/mandarons/icloud-drive-docker/files/12431996/icloud-drive-docker.zip)

**Comment by mandarons** [comment]
To keep it simple, please try below configuration - 

**docker-compose.yaml**
```yaml
version: "3.4"
services:
  icloud:
    image: mandarons/icloud-drive
    env_file:
      - icloud.env #should contain ENV_ICLOUD_PASSWORD=<password>
    container_name: icloud
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/config.yaml:/app/config.yaml
      - ${PWD}/data:/app/icloud
      - ${PWD}/session:/app/session_data
```

For `ENV_ICLOUD_PASSWORD`, use your iCloud login password (i.e. password you use to log into iCloud.com) and not an app password.
