### ISSUE TITLE
[BUG] ERROR :: root :: notify.py :: 45 :: Failed to send email: (550, b'5.7.1 message content rejected').

### ISSUE THREAD

**Issue by dmuiX** [mandarons/icloud-docker#163]
**Describe the bug**
ERROR :: root :: notify.py :: 45 :: Failed to send email: (550, b'5.7.1 message content rejected').

Like the idea. But I get the following error when I start docker-compose 

**To Reproduce**

1. just started with docker-compose -f iCloudBackup.yml up -d

**Expected behavior**

**Screenshots**

**Configuration**
```yaml
app:
  logger:
    level: "debug"
    filename: "icloud.log"
  credentials:
    username: "mali"
    retry_login_interval: 600
  root: "icloud"
  smtp:
    email: "sender"
    to: "receiver"
    password: "pw"
    host: "posteo.de"
    port: 587
    no_tls : false
  region: global
drive:
  destination: "drive"
  remove_obsolete: false
  sync_interval: 300
  ignore:
    - "node_modules"
    - "*.md"
photos:
  destination: "photos"
  remove_obsolete: false
  sync_interval: 500
```
**Additional context**
