### ISSUE TITLE
[BUG] 2023-10-19 22:59:52,160 :: ERROR :: root :: sync.py :: 102 :: Password is not stored in keyring. Please save the password in keyring.

### ISSUE THREAD

**Issue by dmuiX** [mandarons/icloud-docker#164]
**Describe the bug**
System is stopping with this error
Unusable.. -.-
**To Reproduce**

1. docker-compose -f iCloudBackup.yml down
2. delete session_data
3. docker-compose -f iCloudBackup.yml up -d
4. Login via docker exec -it icloud /bin/sh -c 'icloud --username=mail --session-directory=/app/session_data'

**Expected behavior**

**Screenshots**

**Configuration**
```yaml
app:
  logger:
    level: "debug"
    filename: "icloud.log"
  credentials:
    username: "mail"
    retry_login_interval: 10
  root: "icloud"
  region: global
drive:
  destination: "drive"
  remove_obsolete: false
  sync_interval: 30
  ignore:
    - "node_modules"
    - "*.md"
photos:
  destination: "photos"
  remove_obsolete: false
  sync_interval: 30
```

**Additional context**
