### ISSUE TITLE
[BUG] 2023-10-19 23:00:24,456 :: ERROR :: icloudpy.base :: base.py :: 186 :: Missing PCS cookies from the request (423)

### ISSUE THREAD

**Issue by dmuiX** [mandarons/icloud-docker#165]
**Describe the bug**

2023-10-19 23:00:24,456 :: ERROR :: icloudpy.base :: base.py :: 186 :: Missing PCS cookies from the request (423)
Traceback (most recent call last):
  File "/app/./src/main.py", line 7, in <module>
    sync.sync()
  File "/app/src/sync.py", line 74, in sync
    sync_drive.sync_drive(config=config, drive=api.drive)
  File "/app/src/sync_drive.py", line 323, in sync_drive
    items=drive.dir(),
  File "/app/venv/lib/python3.10/site-packages/icloudpy/services/drive.py", line 239, in __getattr__
    return getattr(self.root, attr)
  File "/app/venv/lib/python3.10/site-packages/icloudpy/services/drive.py", line 234, in root
    self, self.get_node_data("FOLDER::com.apple.CloudDocs::root")
  File "/app/venv/lib/python3.10/site-packages/icloudpy/services/drive.py", line 35, in get_node_data
    request = self.session.post(
  File "/app/venv/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 158, in request
    self._raise_error(code, reason)
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 187, in _raise_error
    raise api_error
icloudpy.exceptions.ICloudPyAPIResponseException: Missing PCS cookies from the request (423)

**To Reproduce**

1. docker-compose -f iCloudBackup.yml down
2. delete session_data
3. docker-compose -f iCloudBackup.yml up -d
4. Login via docker exec -it icloud /bin/sh -c 'icloud --username=mail --session-directory=/app/session_data'

**Expected behavior**

**Screenshots**

**Configuration**
```yaml
app:
  logger:
    level: "debug"
    filename: "icloud.log"
  credentials:
    username: "mail"
    retry_login_interval: 10
  root: "icloud"
  region: global
drive:
  destination: "drive"
  remove_obsolete: false
  sync_interval: 30
  ignore:
    - "node_modules"
    - "*.md"
photos:
  destination: "photos"
  remove_obsolete: false
  sync_interval: 30
```
**Additional context**
