### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fishairman90** [mandarons/icloud-docker#169]
Im installing via Unraid. Ive installed, adding my iCloud email to the config. Setup the paths. When it boots, the container acts like it boots right up. Can't seem to connect to the container or view the logs. Seems to be boot looping? 

<img width="1294" alt="Screenshot 2023-11-01 at 9 28 23 PM" src="https://github.com/mandarons/icloud-drive-docker/assets/57339670/6b3eb4aa-c059-439f-b057-0221ef8f7b07">
<img width="523" alt="Screenshot 2023-11-01 at 9 27 56 PM" src="https://github.com/mandarons/icloud-drive-docker/assets/57339670/8d98bda5-2f12-4249-b8a0-cba9e1667a97">

**Comment by mandarons** [comment]
Which version are you using?

**Comment by Fishairman90** [comment]
Hey thanks for the quick reply, usually with Unraid when installing a container if I don’t specify it just downloads the latest. So im 90% it’s the latest? Can’t seem to find the version number anywhere.

When I stopped the container I was able to see the logs. Looks like the .config is full of parser errors. Which is weird because I downloaded the example .config and the only thing I changed was my email. Even line 1 “app:” it has an issue with.. 

￼

**Comment by mandarons** [comment]
Please share your config file.

**Comment by Fishairman90** [comment]
I attached it to the last email? Did it not come through?Justin Peeples First Officer | PSA AirlinesGold Seal Flight Instructor | CFII | IGI1(813)853-4761On Nov 2, 2023, at 10:32, Mandar Patil ***@***.***> wrote:﻿
Please share your config file.

**Comment by mandarons** [comment]
No.

**Comment by Fishairman90** [comment]
Guess it doesn't come through when you reply via email. Let's try this. 

[config.txt](https://github.com/mandarons/icloud-drive-docker/files/13241113/config.txt)

**Comment by mandarons** [comment]
Yeah, it has a lot of garbage characters. Not sure what happened there. Try manually creating `config.yaml` and pasting the content without any garbage characters.

![image](https://github.com/mandarons/icloud-drive-docker/assets/50469173/6cb06869-e884-4c8a-943b-7efd0022cb7e)

**Comment by Fishairman90** [comment]
OMG what is GitHub doing!? Thats not what my .config looks like. It won't let me upload a .yaml and So I pasted it in a txt file.. This is what my config looks like:

https://pastebin.com/84s0hjQy

**Comment by mandarons** [comment]
Try removing/updating -  
1. `drive > filters > folders` list 
2. `drive > filters > file_extensions` list
3. `photos > filters > albums` list

The default values most likely not the ones that you want. Also, this reminds me to make the `config.yaml` copy-paste friendly.

**Comment by Fishairman90** [comment]
Not completely following. Are you saying I can comment everything except the “App” section?

**Comment by mandarons** [comment]
Try below `config.yaml`:

```yaml
app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "icloud.log"
  credentials:
    # iCloud drive username
    username: “justin.peeples@icloud.com”
    # Retry login interval - default is 10 minutes
    retry_login_interval: 600
  # Drive destination
  root: "icloud"
  smtp:
  # If you want to receive email notifications about expired/missing 2FA credentials then uncomment
  # email: "sender@test.com"
  # Uncomment this if your SMTP username is different than your sender address (for services like AWS SES)
  # username: ""
  # default to is same as email above
  # to: "receiver@test.com"
  # password:
  # host: "smtp.test.com"
  # port: 587
  # If your email provider doesn't handle TLS
  # no_tls: true
  # valid values are - global (default - uses .com) or china (uses .com.cn)
  region: global
drive:
  destination: "drive"
  remove_obsolete: false
  sync_interval: 300
  filters:
    # File filters to be included in syncing iCloud drive content
    folders:
    file_extensions:
      # File extensions to be included
photos:
  destination: "photos"
  remove_obsolete: false
  sync_interval: 500
  all_albums: false # Optional, default false. If true preserve album structure. If same photo is in multiple albums creates duplicates on filesystem
  # folder_format: "%Y/%m" # optional, if set put photos in subfolders according to format. Format cheatsheet - https://strftime.org
  filters:
    # List of libraries to download. If omitted (default), photos from all libraries (own and shared) are downloaded. If included, photos only
    # from the listed libraries are downloaded.
    # libraries:
    #   - PrimarySync # Name of the own library
 
    # if all_albums is false - albums list is used as filter-in, if all_albums is true - albums list is used as filter-out
    # if albums list is empty and all_albums is false download all photos to "all" folder. if empty and all_albums is true download all folders
    albums:
    file_sizes:
      # valid values are original, medium and/or thumb
      - "original"
      # - "medium"
      # - "thumb"
```
