### ISSUE TITLE
[BUG] Files are created as root - always

### ISSUE THREAD

**Issue by DorianMazur** [mandarons/icloud-docker#205]
**Describe the bug**
Even if you provide PUID & PGID, the files are created as root.

**To Reproduce**
Docker compose:
```
version: "3.4"
services:
  icloud:
    image: mandarons/icloud-drive:latest
    environment:
      - PUID=1000
      - GUID=1001
      - ENV_ICLOUD_PASSWORD=(your password)
    container_name: icloud
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - (path to config.yaml):/app/config.yaml
      - (path to icloud folder):/app/icloud
      - (path to session_data folder):/app/session_data
      ```
**Expected behavior**
Files should be created as the provided user, not as root
