### ISSUE TITLE
[BUG] s6-rc-compile: fatal: unable to open /etc/s6-overlay/s6-rc.d/svc-icd/up: No such file or directory

### ISSUE THREAD

**Issue by robdejonge** [mandarons/icloud-docker#249]
**Describe the bug**
Container does not seem to be starting. 

**To Reproduce**
My docker-compose.yaml : 

```
services:
  icloud-drive:
    image: mandarons/icloud-drive:main
    environment:
      - PUID=1000
      - GUID=1000
    container_name: icloud-drive
    restart: "no"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/icloud-drive/config.yaml:/app/config.yaml
      - /opt/icloud-drive/log:/app/log
      - /opt/icloud-drive/session_data:/app/session_data
      - /srv/icloud-drive:/app/iCloud/drive
      - 
```

My config.yaml : 

```
app:
  logger: 
    level: "info"
    filename: "/app/log/sync.log"
  credentials:
    username: tim@apple.com
    retry_login_interval: -1
  verbose: true
  root: icloud
drive:
  destination: "drive"
  sync_interval: -1
  remove_obsolete: true
```

After removing existing image and container and thus downloading the latest version, output when I run 'docker compose up' after download looks like this : 

```
 ✔ Container icloud-drive  Created                                                                                             0.2s 
Attaching to icloud-drive
icloud-drive  | s6-rc-compile: fatal: unable to open /etc/s6-overlay/s6-rc.d/svc-icd/up: No such file or directory
```

The container remains up, with the following further information from within : 

```
# ps -ae
    PID TTY          TIME CMD
      1 ?        00:00:00 s6-svscan
     15 ?        00:00:00 s6-supervise
     18 ?        00:00:00 s6-linux-init-s
     33 pts/0    00:00:00 sh
     65 pts/0    00:00:00 ps
# cd /etc/s6-overlay/s6-rc.d
# ls -l svc-icd
total 12
drwxr-xr-x 2 root root 4096 Jul 28 11:30 dependencies.d
-rwxr-xr-x 1 root root   89 Jul 28 11:30 run
-rwxr-xr-x 1 root root    8 Jul 28 11:30 type
# find . -name 'up' -print
./init-custom-files/up
./ci-service-check/up
./init-adduser/up
./init-icd-config/up
./init-migrations/up
./init-services/up
./init-os-end/up
./init-mods-package-install/up
./init-crontab-config/up
./init-config-end/up
./init-mods-end/up
./init-config/up
./init-envfile/up
./init-mods/up
```

I've let it run for 20 minutes and nothing ever happens. 

I'm not sure if I'm doing something wrong in my host config, or if this a recently introduced issue to the image. Apologies if it's the former.
