### ISSUE TITLE
Filter out the "Shared Library" from photo sync

### ISSUE THREAD

**Issue by nicx** [mandarons/icloud-docker#259]
I am running 4 instances of iCloud-docker, every instance stands for one family member. As of today I am syncing all photos of every family member. the regarding config is this:

```
photos:
  destination: "photos"
  remove_obsolete: true
  sync_interval: 14400
  filters:
    albums:
      #- "album1"
      #- "album2"
    file_sizes:
      - "original"
      # - "medium"
      # - "thumb"
```

Now I turned the feature "shared library" on and invited my family members to this library. With that change it seems that every photo in the shared library is synced with every instance of iCloud-docker.

My Question: Is it possible to filter out this shared library, but keep all other albums without specifying them explicitly? If yes, how?

Or in other words, what I want to achieve: I want to get synced all personal libraries of every family member with all albums, and I want to get synced the shared library with all albums only once.

**Comment by mandarons** [comment]
Yes. It is possible to filter out the shared library. Just add `photos > filters > libraries > - PrimarySync` in your `config.yaml`. This will only sync primary library and not shared library.

From [README > Sample Configuration File](https://github.com/mandarons/icloud-docker/blob/main/README.md):

    filters:
    # List of libraries to download. If omitted (default), photos from all libraries (own and shared) are downloaded. If included, photos only
    # from the listed libraries are downloaded.
    # libraries:
    #   - PrimarySync # Name of the own library

    # if all_albums is false - albums list is used as filter-in, if all_albums is true - albums list is used as filter-out
    # if albums list is empty and all_albums is false download all photos to "all" folder. if empty and all_albums is true download all folders
    albums:

**Comment by nicx** [comment]
@mandarons ok thanks. So I will add this option in the config of 3 family members and keep one config withour this option. With that I will get my wish :)

Is the option "all_albums" which I have not configured yet it any config helpful or disruptive in any case?

**Comment by mandarons** [comment]
It depends. 
```
# if all_albums is false - albums list is used as filter-in, if all_albums is true - albums list is used as filter-out
```
It is just a different way of specifying filters. If current configuration is working for you, no need to change it.

**Comment by nicx** [comment]
@mandarons thanks. a last question: If I want to start from scrach because I want to change/use folder_format is it safe just to delete all downloaded photos, then update the config, and then icloud-docker would just redownload all photos again to the new folder structure?

**Comment by mandarons** [comment]
Yes. Deleting and starting over is okay except for one case - if you have `remove_obsolete: false` in your `config.yaml`. In your case, it is `true`. `remove_obsolete` flag tells the app whether to keep files available locally but removed on server, or not.

**Comment by PedroS11** [comment]
Is this still true? I can't download any shared libraries in my account, even I put a shared album in the libraries property, it throws an error

```
app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "/config/icloud.log"
  credentials:
    # iCloud drive username
    username: "EMAIL@gmail.com"
    # Retry login interval - default is 10 minutes, specifying -1 will retry login only once and exit
    retry_login_interval: 60
  # Drive destination
  root: "/icloud"
  telegram:
   bot_token: "TOKEN"
   chat_id: "-ID"
  region: global 
photos:
  destination: "photos"
  # Remove local photos that are not present on server (i.e. photos delete on server)
  remove_obsolete: false
  sync_interval: 60
  all_albums: false # Optional, default false. If true preserve album structure. If same photo is in multiple albums creates duplicates on filesystem
  # folder_format: "%Y-%m" # optional, if set put photos in subfolders according to format. Format cheatsheet - https://strftime.org
  filters:
   file_sizes: # valid values are original, medium and/or thumb
      - "original"
```

This doesn't download the shared albums, if I try to specify a shared one, it fails

```
app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "/config/icloud.log"
  credentials:
    # iCloud drive username
    username: "MAIL@gmail.com"
    # Retry login interval - default is 10 minutes, specifying -1 will retry login only once and exit
    retry_login_interval: 60
  # Drive destination
  root: "/icloud"
  telegram:
   bot_token: "TOKEN"
   chat_id: "-CHATID"
  region: global # For China server users, set this to - china (default: global)
photos:
  destination: "photos"
  # Remove local photos that are not present on server (i.e. photos delete on server)
  remove_obsolete: false
  sync_interval: 60
  all_albums: false # Optional, default false. If true preserve album structure. If same photo is in multiple albums creates duplicates on filesystem
  # folder_format: "%Y-%m" # optional, if set put photos in subfolders according to format. Format cheatsheet - https://strftime.org
  filters:
   libraries:
     - SharedSync-9DD9B767-XXXXXXXX
   file_sizes: # valid values are original, medium and/or thumb
      - "original"
```

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/78c5a896-3a28-4c89-9a20-8a3a38b236fa" />

Can someone help? Having the possibility to include shared libraries would be perfecct
