### ISSUE TITLE
[BUG] Keep telling me "authentication required for account. (421)" in unRAID docker

### ISSUE THREAD

**Issue by sarcomattys** [mandarons/icloud-docker#275]
**Describe the bug**
Environment: unRAID docker
I installed icloud-docker and updated the password during installation process. I created config.yaml file under /config and the /icloud folder was created and accessible. Mapping is fine per unRAID.

I also used the following command to log in with password and 6-digt 2FA code filled in :
`
docker exec -it icloud /bin/sh -c "icloud --username=XXX --region=china --session-directory=/config/session_data"
`

I never successfully started the service to sync. 

**To Reproduce**
However, restarting the cloud docker in unRAID, it kept telling me this error in log file:
`
2024-12-02 14:10:54,580 :: INFO :: root :: sync.py :: 82 :: Syncing drive...
2024-12-02 14:10:55,087 :: ERROR :: icloudpy.base :: base.py :: 186 :: Authentication required for Account. (421)
`

No matter how repeatedly I have been using the command mentioned above (no error message received), still I got the error messages and icloud is unable to sync. 

**Expected behavior**
Could you please help let me know the step to go through "authentication required for account" message. Thanks

**Configuration**
config.yaml file as follows:

```                                                   
app:
  logger:
    level: "info"
    filename: "/config/icloud.log"
  credentials:
    username: "XXX"
  retry_login_interval: 600
  root: "/icloud"
  region: "china"
drive:
  destination: "drive"
  remove_obsolete: false
  sync_interval: 300
  filters:
    folders:
      - "Documents"
    file_extensions:
      # File extensions to be included
      - "pdf"
      - "pptx"
      - "xlsx"
      - "docx"
```
