### ISSUE TITLE
[BUG] Error: 2FA is required. Please log in.

### ISSUE THREAD

**Issue by anfractuosity** [mandarons/icloud-docker#278]
**Describe the bug**

I thought this may have possibly been fixed as I saw recent changes to both icloudpy and icloud-docker, however, I still appear
to get a 2FA error.

**To Reproduce**
```
docker-compose pull
docker-compose up
```

```
icloud  | 2024-12-08 14:44:41,571 :: ERROR :: icloudpy.base :: base.py :: 180 :: Authentication required for Account. (421)
icloud  | 2024-12-08 14:44:43,509 :: ERROR :: root :: sync.py :: 87 :: Error: 2FA is required. Please log in.
```

I get a passcode notification on the iphone when running `docker-compose up` 

And then use:
```
docker exec -it icloud /bin/sh -c "icloud --username=<EMAIL> --session-directory=/app/session_data"
```

I've noticed sometimes this doesn't even seem to prompt for a code, so am a bit confused.

I then wait for it to re-try logging in, I set to 180s.  It then seems to give me another code on my phone.

But when I use the 2fa command, it doesn't give a prompt to enter the code.

**Expected behavior**
No 2FA error

**Configuration**
I use the following docker-compose.yml:

```
services:
  icloud:
    image: mandarons/icloud-drive
    environment:
      - PUID=1000
      - GUID=1000
    env_file:
      - .env.icloud #should contain ENV_ICLOUD_PASSWORD=<password>
    container_name: icloud
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/config.yaml:/app/config.yaml
      - ${PWD}/icloud/data:/app/icloud
      - ${PWD}/session_data:/app/session_data
```
