### ISSUE TITLE
[BUG] Bad username or password

### ISSUE THREAD

**Issue by dploeger** [mandarons/icloud-docker#280]
**Describe the bug**
After the tool has worked without any problems, I now get a "bad username or password" when trying to trigger the 2fa.

I've pulled the latest image tag but the problem persists. I have a 2fa enabled account, logging in on icloud.com works without a problem. Maybe Apple changed something on their side?

**To Reproduce**

1. Set up icloud-docker with a 2fa enabled account
2. Run the authentication command `docker exec -it icloud /bin/sh -c "icloud --username=emailaddress --session-directory=/config/session_data"` 

**Expected behavior**
The 2fa request would trigger and I can log in without a problem.

**Configuration**
If applicable, please share the configuration details

``` 
app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "icloud.log"
  credentials:
    # iCloud drive username
    username: "redacted"
    # Retry login interval - default is 10 minutes
    retry_login_interval: 600
  # Drive destination
  root: "icloud"
  smtp:
    ## If you want to receive email notifications about expired/missing 2FA credentials then uncomment
    email: "redacted"
    ## optional, to email address. Default is sender email.
    # to: "receiver@test.com"
    username: "redacted"
    password: "redacted"
    host: "redacted"
    port: 25
    # host: "smtp.test.com"
    # port: 587
    # If your email provider doesn't handle TLS
    no_tls: false
  region: global # For China server users, set this to - china (default: global)
  telegram:
    bot_token: redacted
    chat_id: redacted 
drive:
  destination: "drive"
  remove_obsolete: true
  sync_interval: 300
  #filters: # Optional - use it only if you want to download specific folders.
    # File filters to be included in syncing iCloud drive content
    #folders:
    #  - "Curve"
photos:
  destination: "photos"
  remove_obsolete: true
  sync_interval: 500
  all_albums: true # Optional, default false. If true preserve album structure. If same photo is in multiple albums creates duplicates on filesystem
  #folder_format: "%Y/%m" # optional, if set put photos in subfolders according to format. Format cheatsheet - https://strftime.org
  #filters:
    # List of libraries to download. If omitted (default), photos from all libraries (own and shared) are downloaded. If included, photos only
    # from the listed libraries are downloaded.
    # libraries:
    #   - PrimarySync # Name of the own library

    # if all_albums is false - albums list is used as filter-in, if all_albums is true - albums list is used as filter-out
    # if albums list is empty and all_albums is false download all photos to "all" folder. if empty and all_albums is true download all folders
    #albums:
    #  - "Avatars"
    #file_sizes: # valid values are original, medium and/or thumb
    #  - "original"
``` 

**Additional context**

**Comment by DrJeff** [comment]
same here no config changes but same login issue

**Comment by Bytechanger** [comment]
same here

**Comment by dploeger** [comment]
@mandarons Any idea about this?

**Comment by mandarons** [comment]
Try this:

1. Delete `session_data` directory
2. Run `docker exec -it --user=abc icloud /bin/sh -c "icloud --username=<icloud-username> --session-directory=/config/session_data"` (Note the `--user=abc` parameter in the command).

**Comment by hyprsh** [comment]
I got the same error, deleted session_data & tried your command but still not able to log in:

```bash
docker exec -it --user=abc icloud /bin/sh -c "icloud --username=blabla@bla.com --session-directory=/config/session_data"
Enter iCloud password for blabla@bla.com:
Bad username or password for blabla@bla.com
```

icloud.com the same credentials work.

**Comment by hyprsh** [comment]
i found the solution... It seems my account was locked.. so i had to reset the password via iforgot.apple.com . Know everything works. Unfortunately, when you login via https://icloud.com, no error message shows up

Maybe there should be a more verbose error message to catch this.

**Comment by robdejonge** [comment]
I still experience this issue, but have seen references to it in this and many other tickets and also some comments that it should now have been resolved. Asking @mandarons if I should add my config files and such to this or a specific other ticket my case with similar symptoms, or if opening a new ticket is preferred?

I have already tried deleting images, session data, etc. and also (literally) the `--user=abc` recommendation above.

**Comment by mandarons** [comment]
@robdejonge Please feel free to add more details here. Not sure what's going on with your setup.

**Comment by robdejonge** [comment]
Thanks or your help, @mandarons. 

My docker-compose.yaml: 
```
services:
  icloud-drive:
    image: mandarons/icloud-drive
    environment:
      - PUID=1000
      - PGID=1000
      - ENV_CONFIG_FILE_PATH=/config/config.yaml
    container_name: icloud-drive
    restart: "no"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/icloud-drive:/config
      - /srv/icloud-drive-backup:/icloud/drive
```

My config.yaml: 
```
app:
  logger: 
    level: "info"
    filename: "/config/sync.log"
  credentials:
    username: myusername@icloud.com
    retry_login_interval: 300 # normal operation I set this to -1
  verbose: true
  root: "/icloud"
drive:
  destination: "drive"
  sync_interval: 300 # normal operation I set this to -1
  remove_obsolete: true
```

Refresh steps:

1. Remove the contents of the `session_data` directory. 
2. Remove all related Docker images to ensure the latest gets used. 
3. `docker compose up`
4. A bunch of images get pulled down and the container comes up. 
5. `docker exec -it icloud-drive /bin/sh -c "icloud --username=myusername@icloud.com --session-directory=/config/session_data"`

The output I get is: 
**Bad username or password for myusername@icloud.com**

I have checked if `/lsiopy/bin/icloud` has a verbose output option, but it does not seem to. The sync log shows no entries when I try to enter the password. I am 100% certain I am entering the correct password. 

I'm at my wits end. Thanks very much for taking a look at this!
