### ISSUE TITLE
Cannot get app to use the correct config file. Will not store icloud authentication.

### ISSUE THREAD

**Issue by mullermn** [mandarons/icloud-docker#287]
Hi,

I have read through the many bug reports/requests on very similar topics here and as far as I can tell I've done everything I could possibly need to do, but I cannot get this app to recognise the correct config path. Whatever I do, it loads the one from /app inside the container (I have validated this by changing that file's debug level setting).

I have:
- Set up the compose file:
```
services:
  icloud:
    image: mandarons/icloud-drive
    environment:
      - PUID=1234
      - PGID=1234
      - ENV_CONFIG_FILE_PATH = /config/config.yaml
    container_name: me-icloud-sync
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/me/iCloud:/icloud
      - /home/me/.config/icloud-docker/config:/config # Must contain config.yaml
```

- Confirmed the environment variable is being set inside the container.
![Image](https://github.com/user-attachments/assets/b92587d6-5550-4a16-bcef-7c5c3763faa5)

- Created the folder and put a config file there

- Confirmed that the correct folder and file is available on the correct path inside the container
![Image](https://github.com/user-attachments/assets/c26b4134-e0c8-4071-974f-eec73340f691)

Not sure what else I can possibly have to do? Can someone assist while I still have some hair left, please?

On a related note - I think the debug level output could be a bit more helpful; it doesn't currently tell you what configuration is making its way through to the app.

Thanks
