### ISSUE TITLE
[QUESTION/BUG?] Very slow sync speed

### ISSUE THREAD

**Issue by JobeanSmith** [mandarons/icloud-docker#300]
**Describe the bug**
I have installed iCloud-Docker on TrueNAS Scale, and after some configuration, it works just fine. However, when the download started, I noticed that the download speed for syncing/downloading files is very slow. I’m averaging around 10 KB/s, and after 24 hours, I’ve only downloaded 3.74 GB.
I have 700 GB on iCloud, which means it would take about 200 days to sync everything—this seems abnormal.
Is this a normal download speed? I have a good internet connection (500 Mbps), and nothing else is using the bandwidth, so there shouldn’t be any interference.

**To Reproduce**
Simply set up and run the docker image (via UI then shell to log in).

**Configuration**
Advanced Data Protection : disabled
Access iCloud via web : enabled
Two Factor Authentication : enabled

Here is my .env.icloud :
`ENV_CONFIG_FILE_PATH=/config/config.yaml`

Here is my config.yaml :
```
app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "/config/icloud.log"
  credentials:
    # iCloud drive username
    username: "mail"
    # Retry login interval - default is 10 minutes, specifying -1 will retry login only once and exit
    retry_login_interval: 600
  # Drive destination
  root: "/iCloud"
  # discord:
  # webhook_url: <your server webhook URL here>
  # username: icloud-docker #or any other name you prefer
  # telegram:
  # bot_token: <your Telegram bot token>
  # chat_id: <your Telegram user or chat ID>
  # pushover:
  # user_key: <your Pushover user key>
  # api_token: <your Pushover api token>
  smtp:
    ## If you want to receive email notifications about expired/missing 2FA credentials then uncomment
    email: "mail"
    ## optional, to email address. Default is sender email.
    # to: "receiver@test.com"
    password: "password"
    host: "host"
    port: port
    # If your email provider doesn't handle TLS
    no_tls: false
  region: global # For China server users, set this to - china (default: global)
drive:
  destination: "Drive"
  # Remove local files that are not present on server (i.e. files delete on server)
  remove_obsolete: true
  sync_interval: 592200
  # filters: # Optional - use it only if you want to download specific folders.
    # File filters to be included in syncing iCloud drive content
    # folders:
      # - "folder1"
      # - "folder2"
      # - "folder3"
    # file_extensions:
      # File extensions to be included
      # - "pdf"
      # - "png"
      # - "jpg"
      # - "jpeg"
  # ignore:
    # When specifying folder paths, append it with /*
    # - "node_modules/*"
    # - "*.md"
photos:
  destination: "Photos"
  # Remove local photos that are not present on server (i.e. photos delete on server)
  remove_obsolete: true
  sync_interval: 592200
  all_albums: false # Optional, default false. If true preserve album structure. If same photo is in multiple albums creates duplicates on filesystem
  folder_format: "%Y/%m" # optional, if set put photos in subfolders according to format. Format cheatsheet - https://strftime.org
  filters:
    # List of libraries to download. If omitted (default), photos from all libraries (own and shared) are downloaded. If included, photos only
    # from the listed libraries are downloaded.
    # libraries:
    #   - PrimarySync # Name of the own library

    # if all_albums is false - albums list is used as filter-in, if all_albums is true - albums list is used as filter-out
    # if albums list is empty and all_albums is false download all photos to "all" folder. if empty and all_albums is true download all folders
    # albums:
      # - "album 1"
      # - "album2"
    file_sizes: # valid values are original, medium and/or thumb
      - "original"
      # - "medium"
      # - "thumb"
    # extensions: # Optional, media extensions to be included in syncing iCloud Photos content
      # - jpg
      # - heic
      # - png
```

The command to run the docker:
`sudo docker exec -it --user=abc icloud /bin/sh -c "icloud --username=mail --session-directory=/config/session_data"`
