### ISSUE TITLE
[QUESTION/BUG] Shared albums aren't downloaded by default

### ISSUE THREAD

**Issue by PedroS11** [mandarons/icloud-docker#302]
I'm trying to run this using Docker. I successfully connected to Icloud, but my downloaded photos do not include my Shared albums. Am I missing something in my config?

```
app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "/config/icloud.log"
  credentials:
    # iCloud drive username
    username: "myemail@gmail.com"
    # Retry login interval - default is 10 minutes, specifying -1 will retry login only once and exit
    retry_login_interval: 3600
  # Drive destination
  root: "/icloud"
  telegram:
   bot_token: "TOKEN"
   chat_id: "-CHATID"
  region: global # For China server users, set this to - china (default: global)
photos:
  destination: "photos"
  # Remove local photos that are not present on server (i.e. photos delete on server)
  remove_obsolete: false
  sync_interval: 1800
  all_albums: true # Optional, default false. If true preserve album structure. If same photo is in multiple albums creates duplicates on filesystem
  # folder_format: "%Y-%m" # optional, if set put photos in subfolders according to format. Format cheatsheet - https://strftime.org
  filters:
    # List of libraries to download. If omitted (default), photos from all libraries (own and shared) are downloaded. If included, photos only
    # from the listed libraries are downloaded.
    # libraries:
    #   - PrimarySync # Name of the own library

    # if all_albums is false - albums list is used as filter-in, if all_albums is true - albums list is used as filter-out
    # if albums list is empty and all_albums is false download all photos to "all" folder. if empty and all_albums is true download all folders
    albums:
    #  - "Test"
    file_sizes: # valid values are original, medium and/or thumb
      - "original"
      # - "medium"
      # - "thumb"
    extensions: # Optional, media extensions to be included in syncing iCloud Photos content
    # - jpg
    # - heic
    # - png

```

**Comment by PedroS11** [comment]
I tried to hardcode a valid SharedSync album (accessed my cloud account, opened a shared album, got the uuid from the URL and appended SharedSync to it but got no luck.


This doesn't download the shared albums, if I try to specify a shared one, it fails

```
app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "/config/icloud.log"
  credentials:
    # iCloud drive username
    username: "MAIL@gmail.com"
    # Retry login interval - default is 10 minutes, specifying -1 will retry login only once and exit
    retry_login_interval: 60
  # Drive destination
  root: "/icloud"
  telegram:
   bot_token: "TOKEN"
   chat_id: "-CHATID"
  region: global # For China server users, set this to - china (default: global)
photos:
  destination: "photos"
  # Remove local photos that are not present on server (i.e. photos delete on server)
  remove_obsolete: false
  sync_interval: 60
  all_albums: false # Optional, default false. If true preserve album structure. If same photo is in multiple albums creates duplicates on filesystem
  # folder_format: "%Y-%m" # optional, if set put photos in subfolders according to format. Format cheatsheet - https://strftime.org
  filters:
   libraries:
     - SharedSync-9DD9B767-XXXXXXXX
   file_sizes: # valid values are original, medium and/or thumb
      - "original"
```

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/78c5a896-3a28-4c89-9a20-8a3a38b236fa" />
