### ISSUE TITLE
Add user: $UID:$GID to docker compose

### ISSUE THREAD

**Issue by AlexMikhalev** [mandarons/icloud-docker#5]
Proposal 
add 
user: $UID:$GID to docker-compose or docker run commands to prevent iCloud files being synced under root.
```
export UID=$(id -u)
export GID=$(id -g)
```
and docker-compose sampled changed:
```
version: "3.4"
services:
  icloud-drive:
    user: $UID:$GID
    image: mandarons/icloud-drive
    container_name: icloud-drive
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/icloud-drive/config.yaml:/app/config.yaml
      - ${PWD}/icloud-drive/drive:/app/drive
```
