### ISSUE TITLE
[BUG] No photos configuration, but all are downloaded

### ISSUE THREAD

**Issue by robdejonge** [mandarons/icloud-docker#52]
**Describe the bug**
Although the configuration file has separate sections to configure the download of drive and of photos, omitting the photos section does not seem to omit the download of all photos. This could be by design, but seemed counterintuitive to me. Especially because it seems the `photos` section does not seem to have a disable setting, or a filter that would match all files possible. 

**To Reproduce**
1. Run the container with a configuration file that does not have a photos clause, for example as per below. 

**Expected behavior**
I would expect the program to download only the files for the clause configured. 

**Configuration**
```
app:                                                                                                                            
  credentials:                                                                                                                  
    username: xxx                                                                                             
  sync_interval: 300
  root: icloud
  verbose: true
drive:
  destination: drive
  remove_obsolete: true
```
