### ISSUE TITLE
[BUG] error when processing filtered folders when name is a number

### ISSUE THREAD

**Issue by marcovn** [mandarons/icloud-docker#63]
If you want to filter drive folders that have a numeric name (e.g. "2022") the code fails and stops processing.

Create a folder named 2022 and put some files in there. Configure config.yaml something like this:

```
drive:
  # Destination to store iCloud drive data locally
  destination: drive
  # Whether to remove local files that are not present on server
  remove_obsolete: false
  filters:
    # Folder filters to be included in syncing iCloud drive content
    folders:
      - 2022
```

Now when you run the container the error below will be shown.

```
icloud    | Loading config from /app/config.yaml ...
icloud    | Enabled verbose ...
icloud    | Checking drive destination ...
icloud    | Checking root destination ...
icloud    | Not Removing obsolete files and folders ...
icloud    | Traceback (most recent call last):
icloud    |   File "/app/./src/main.py", line 6, in <module>
icloud    |     sync.sync()
icloud    |   File "/app/src/sync.py", line 21, in sync
icloud    |     sync_drive.sync_drive(
icloud    |   File "/app/src/sync_drive.py", line 205, in sync_drive
icloud    |     return sync_directory(
icloud    |   File "/app/src/sync_drive.py", line 155, in sync_directory
icloud    |     new_folder = process_folder(
icloud    |   File "/app/src/sync_drive.py", line 66, in process_folder
icloud    |     if not wanted_folder(
icloud    |   File "/app/src/sync_drive.py", line 35, in wanted_folder
icloud    |     os.path.abspath(root), folder.removeprefix("/").removesuffix("/")
icloud    | AttributeError: 'int' object has no attribute 'removeprefix'
icloud exited with code 1
```
