### ISSUE TITLE
SMTP server closes connection

### ISSUE THREAD

**Issue by natelandau** [mandarons/icloud-docker#72]
First off, thank you so much for this fantastic project.  It is exactly what I was looking for without even knowing I was looking for it. 

**Describe the bug**
When booting the container I do not receive an email that my account credentials are not available.   I see this error n the logs:

```
2022-02-19 16:20:14,992 :: ERROR :: root :: notify.py :: 39 :: Failed to send email: Connection unexpectedly closed
```

 I have rechecked my SMTP address, username, password, and port multiple times.  I have also switch the `no_tls` from `true` to `false` and back without any difference.  In addition, I tested SMTP access with these credentials from my email client and they work without issue

Here's the relevant part of the config

```
smtp:
  # If you want to recieve email notifications about expired/missing 2FA credentials then uncomment
  email: "[email_address]"
  password: "[password]"
  host: "smtp.fastmail.com"
  port: 465
  # If your email provider doesn't handle TLS
  no_tls: false
```

**To Reproduce**
1. Set an app specific password in Fastmail with SMTP access
2. Add relevant information to configuration file
3. Boot this container
4. See the error above in the logs

**Expected behavior**
Receiving an email when the container first boots and the iCloud account is not yet granted access
