### ISSUE TITLE
[BUG] Error during 2FA authentification

### ISSUE THREAD

**Issue by xiaotianxt** [mandarons/icloud-docker#78]
**Describe the bug**
After execting the login command given in `README.md`
```bash
docker exec -it icloud /bin/sh -c "icloud --username=xxxx --session-directory=/app/session_data"
```
The following error shows:
```
tian@dorm-synology:/volume1/docker/icloud-drive$ sudo docker exec -it icloud /bin/sh -c "icloud --username=testtest@testtest.com --session-directory=/app/session_data"
Enter iCloud password for testest@testtest.com:
Traceback (most recent call last):
  File "/app/venv/bin//icloud", line 8, in <module>
    sys.exit(main())
  File "/app/venv/lib/python3.9/site-packages/icloudpy/cmdline.py", line 207, in main
    api = ICloudPyService(
  File "/app/venv/lib/python3.9/site-packages/icloudpy/base.py", line 273, in __init__
    self.authenticate()
  File "/app/venv/lib/python3.9/site-packages/icloudpy/base.py", line 344, in authenticate
    self._webservices = self.data["webservices"]
KeyError: 'webservices'
```

**To Reproduce**
1. Execute the command above.
2. See error

**Configuration**
If applicable, please share the configuration details

docker-compose.yaml:
```yaml
version: "3.4"
services:
  icloud:
    image: mandarons/icloud-drive
    environment:
      - PUID=1026
      - GUID=100
    env_file:
      - /volume1/docker/icloud-drive/.env.icloud
    container_name: icloud
    restart: unless-stopped
    volumes:
      - /volume1/docker/icloud-drive/config.yaml:/app/config.yaml
      - /volume2/Onedrive/icloud:/app/icloud/drive
      - /volume1/docker/icloud-drive/session_data:/app/session_data
```

config.yaml:
```yaml
app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "icloud.log"
  credentials:
    # iCloud drive username
    username: "testest@testtest.com"
    # Retry login interval - default is 10 minutes
    retry_login_interval: 600
  # Drive destination
  root: "icloud"
  smtp:
    ...
drive:
  destination: "drive"
  remove_obsolete: false
  sync_interval: 300
```

**Comment by mandarons** [comment]
@xiaotianxt is it still a valid bug? Sorry, I didn't get a chance to look at it until now. I am not able to reproduce it.

**Comment by iPixelOldC** [comment]
> @xiaotianxt is it still a valid bug? Sorry, I didn't get a chance to look at it until now. I am not able to reproduce it.

yeah, I also encountered this problem. And the pop-up window of 2fa on my mobile phone appeared, but the same error was also reported. 
But if you don't appear, I guess it's because Xiao and I both use the Chinese version of iCloud(云上贵州). Maybe that's the problem.
As far as I know, their domain names are different. We use https://www.icloud.com.cn

```
version: "3.4"
services:
  icloud:
    image: mandarons/icloud-drive
    environment:
      - PUID=1000
      - GUID=1000
    container_name: icloud
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/zxzx/.config/icloud/config.yaml:/app/config.yaml
      - /home/zxzx/share/icloud/data:/app/icloud
      - /home/zxzx/.config/icloud/session_data:/app/session_data
```

config.yaml same

```
/app # icloud --username=*** --session-directory=/app/session_data
Enter iCloud password for ***: 
Traceback (most recent call last):
  File "/app/venv/bin//icloud", line 8, in <module>
    sys.exit(main())
  File "/app/venv/lib/python3.9/site-packages/icloudpy/cmdline.py", line 207, in main
    api = ICloudPyService(
  File "/app/venv/lib/python3.9/site-packages/icloudpy/base.py", line 273, in __init__
    self.authenticate()
  File "/app/venv/lib/python3.9/site-packages/icloudpy/base.py", line 344, in authenticate
    self._webservices = self.data["webservices"]
KeyError: 'webservices'
```

**Comment by mandarons** [comment]
@iPixelOldC : Yes! Now that makes a lot more sense to me. It looks like iCloud.com.cn has some different structure for iCloud webservices. Do you mind helping me to confirm that? I would like to see a dump of `self.data` variable shown in the error.

**Comment by iPixelOldC** [comment]
@mandarons Sure, what should I do?

And I found [icloudpd](https://github.com/boredazfcuk/docker-icloudpd) supports the iCloud CN. Looking at the source code, it just [replaces the domain name](https://github.com/boredazfcuk/docker-icloudpd/blob/b9b0a4feb4bf284974acc62da46e29d7733d4553/sync-icloud.sh#L163). Then I use his container. After opening the [support](https://github.com/boredazfcuk/docker-icloudpd/blob/b9b0a4feb4bf284974acc62da46e29d7733d4553/README.md?plain=1#L73), it can work.

**Comment by mandarons** [comment]
1. Run the following command inside container -
`sed -i -e "s#icloud.com/#icloud.com.cn/#" -e "s#icloud.com'#icloud.com.cn'#" "$(pip show icloudpy | grep "Location" | awk '{print $2}')/icloudpy/base.py"`
2. Then try to reproduce the error again

**Comment by iPixelOldC** [comment]
It seems to work, but it still needs to be modified in one place, otherwise it will report the same webservices error.

```
sed -i -e "s#icloud.com/#icloud.com.cn/#" -e "s#icloud.com'#icloud.com.cn'#" "$(pip show icloudpy | grep "Location" | awk '{print $2}')/icloudpy/base.py"
cd /app/venv/lib/python3.9/site-packages/icloudpy
vi base.py
```
then modify HOME_ENDPOINT (I don't know why it hasn't been modified by sed command)
```
class ICloudPyService(object):                                                   
    """                                                                          
    A base authentication class for the iCloud service. Handles the              
    authentication required to access iCloud services.                           
                                                                                 
    Usage:                                                                       
        from src import ICloudPyService                                          
        icloudpy = ICloudPyService('username@apple.com', 'password')             
        icloudpy.iphone.location()                                               
    """                                                                          
                                                                                 
    AUTH_ENDPOINT = "https://idmsa.apple.com/appleauth/auth"                     
    HOME_ENDPOINT = "https://www.icloud.com"                                  
    SETUP_ENDPOINT = "https://setup.icloud.com.cn/setup/ws/1"
```
to
```
class ICloudPyService(object):                                                   
    """                                                                          
    A base authentication class for the iCloud service. Handles the              
    authentication required to access iCloud services.                           
                                                                                 
    Usage:                                                                       
        from src import ICloudPyService                                          
        icloudpy = ICloudPyService('username@apple.com', 'password')             
        icloudpy.iphone.location()                                               
    """                                                                          
                                                                                 
    AUTH_ENDPOINT = "https://idmsa.apple.com/appleauth/auth"                     
    HOME_ENDPOINT = "https://www.icloud.com.cn"                                  
    SETUP_ENDPOINT = "https://setup.icloud.com.cn/setup/ws/1"
```
It's work. Photos are also starting to download。
```
/app # icloud --username=xxx --session-directory=/app/session_data
Bad username or password for xxx
Enter iCloud password for xxx: 
Save password in keyring? [y/N]: y

Two-step authentication required. 
Please enter validation code
(string) --> 000000

/app 
```
```
2022-07-16 12:09:45,044 :: INFO :: root :: sync_photos.py :: 37 :: Downloading /app/icloud/photos/哔哩哔哩/IMG_4634.JPG ...

2022-07-16 12:09:48,792 :: INFO :: root :: sync_photos.py :: 37 :: Downloading /app/icloud/photos/哔哩哔哩/IMG_4633.JPG ...

2022-07-16 12:09:53,130 :: INFO :: root :: sync_photos.py :: 37 :: Downloading /app/icloud/photos/哔哩哔哩/IMG_4632.JPG ...

2022-07-16 12:09:56,400 :: INFO :: root :: sync_photos.py :: 37 :: Downloading /app/icloud/photos/哔哩哔哩/IMG_4631.JPG ...

2022-07-16 12:09:57,214 :: INFO :: root :: sync_photos.py :: 37 :: Downloading /app/icloud/photos/哔哩哔哩/IMG_4630.JPG ...

2022-07-16 12:09:57,660 :: INFO :: root :: sync_photos.py :: 37 :: Downloading /app/icloud/photos/哔哩哔哩/IMG_4629.JPG ...

2022-07-16 12:09:58,576 :: INFO :: root :: sync_photos.py :: 37 :: Downloading /app/icloud/photos/哔哩哔哩/IMG_4628.JPG ...

2022-07-16 12:09:59,231 :: INFO :: root :: sync_photos.py :: 37 :: Downloading /app/icloud/photos/哔哩哔哩/IMG_4627.JPG ...

2022-07-16 12:09:59,625 :: INFO :: root :: sync_photos.py :: 37 :: Downloading /app/icloud/photos/哔哩哔哩/IMG_4626.JPG ...

```

**Comment by mandarons** [comment]
@iPixelOldC That's a great news! I know how to fix it now. Thank you for helping me identify the root cause. I will create a build for you to test soon.

**Comment by mandarons** [comment]
@iPixelOldC : please try with `docker pull mandarons/icloud-drive:main` and see if that fixes the issue.

**Comment by iPixelOldC** [comment]
@mandarons same webservices error. But I can use it after repeating the above operation (sed -i -e "s#icl... vi base.py...). This 'region: china' parameter may not be work?

```
/app # icloud --username=xxx --session-directory=/app/session_data
Enter iCloud password for xxx: 
Traceback (most recent call last):
  File "/app/venv/bin//icloud", line 8, in <module>
    sys.exit(main())
  File "/app/venv/lib/python3.9/site-packages/icloudpy/cmdline.py", line 226, in main
    else ICloudPyService(
  File "/app/venv/lib/python3.9/site-packages/icloudpy/base.py", line 277, in __init__
    self.authenticate()
  File "/app/venv/lib/python3.9/site-packages/icloudpy/base.py", line 348, in authenticate
    self._webservices = self.data["webservices"]
KeyError: 'webservices'
```
```
app:
  logger:
    # level - debug, info (default), warning or error
    level: "info"
    # log filename icloud.log (default)
    filename: "icloud.log"
  credentials:
    # iCloud drive username
    username: "xxx"
    # Retry login interval - default is 10 minutes
    retry_login_interval: 600
  # Drive destination
  root: "icloud"
  smtp:
  region: china
drive:
  destination: "drive"
  remove_obsolete: false
  sync_interval: 300
  filters:
    # File filters to be included in syncing iCloud drive content
    folders:
      - "KyBook 3"
      - "Downloads"
      - "文稿"
    file_extensions:
      # File extensions to be included
      - "pdf"
      - "png"
      - "jpg"
      - "jpeg"
photos:
  destination: "photos"
  remove_obsolete: false
  sync_inteval: 500
  filters:
    albums:
      - "Yealico"
      # - "微博"
    file_sizes: # valid values are original, medium and/or thumb
      - "original"
      # - "medium"
      # - "thumb"
```
```
version: "3.4"
services:
  icloud:
    image: mandarons/icloud-drive:main
    environment:
      - PUID=1000
      - GUID=1000
    container_name: icloud
    restart: unless-stopped
    volumes:

      - /home/zxzx/.config/icloud2/config.yaml:/app/config.yaml
      - /home/zxzx/share/icloud/data:/app/icloud
      - /home/zxzx/.config/icloud2/session_data:/app/session_data
```
base.py
```
    def __init__(
        self,
        apple_id,
        password=None,
        cookie_directory=None,
        verify=True,
        client_id=None,
        with_family=True,
        auth_endpoint="https://idmsa.apple.com/appleauth/auth",
        # For China, use "https://www.icloud.com.cn"
        home_endpoint="https://www.icloud.com.cn",
        # For China, use "https://setup.icloud.com.cn/setup/ws/1"
        setup_endpoint="https://setup.icloud.com.cn/setup/ws/1",
    ):
```
